// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package log

import (
	"github.com/google/wire"
	"github.com/pkg/errors"
	"go.uber.org/zap"
)

// Injectors from providers.go:

func InjectDebug() (*Service, error) {
	service, err := NewDebug()
	if err != nil {
		return nil, err
	}
	return service, nil
}

func InjectVerbose() (*Service, error) {
	service, err := NewVerbose()
	if err != nil {
		return nil, err
	}
	return service, nil
}

// providers.go:

func NewVerbose() (*Service, error) {
	l, err := zap.NewDevelopment()
	if err != nil {
		return nil, errors.WithStack(err)
	}
	zap.ReplaceGlobals(l)
	return &Service{
		Z:    l,
		mode: LoggingVerbose,
	}, nil
}

func NewDebug() (*Service, error) {
	l, err := zap.NewDevelopment()
	if err != nil {
		return nil, errors.WithStack(err)
	}
	zap.ReplaceGlobals(l)
	return &Service{
		Z:    l,
		mode: LoggingDebug,
	}, nil
}

var DebugSet = wire.NewSet(
	NewDebug,
)

var VerboseSet = wire.NewSet(
	NewVerbose,
)
