// Code generated by github.com/izumin5210/gex. DO NOT EDIT.

// +build tools

package _snapshots_mod

// tool dependencies
import (
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway"
)

