// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package hack

import (
	"github.com/gofunct/iio"
	"github.com/google/wire"
)

// Injectors from providers.go:

func Inject() *Service {
	service := New()
	return service
}

// providers.go:

// New returns a new Interface which will os/exec to run commands.
func New() *Service {
	return &Service{
		io: iio.NewStdIO(),
	}
}

var Provider = wire.NewSet(
	New,
)
