// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package ask

import (
	"github.com/gofunct/iio"
	"github.com/google/wire"
	"github.com/tcnksm/go-input"
)

// Injectors from providers.go:

func Inject() (*Service, error) {
	service, err := iio.Inject()
	if err != nil {
		return nil, err
	}
	askService := New(service)
	return askService, nil
}

// providers.go:

func NewDefault() *Service {
	return &Service{
		Q: input.DefaultUI(),
	}
}

func New(i *iio.Service) *Service {
	return &Service{
		Q: &input.UI{
			Writer: i.Out(),
			Reader: i.In(),
		},
	}
}

var Providers = wire.NewSet(iio.Inject, New)
